package:
  - tidyverse
  - tidymodels
  - rvest
  - webdriver
  - RSelenium
  - glue
  - lubridate
  - magrittr
  - GGally
  - ggridges
  - Cairo
urls:
  top: https://www.jleague.jp/
  club-top: https://www.jleague.jp/club/
